
# state vectors of a moving object with changing properties

t=0: [x_0, y_0, z_0, "A"]
t=1: [x_1, y_1, z_1, "A"]
t=2: [x_2, y_2, z_2, "A"]
t=3: [x_3, y_3, z_3, "A"]
t=4: [x_4, y_4, z_4, "A"]
t=5: [x_5, y_5, z_5, "B"]
t=6: [x_6, y_6, z_6, "B"]
t=7: [x_7, y_7, z_7, "B"]
t=8: [x_8, y_8, z_8, "B"]
t=9: [x_9, y_9, z_9, "B"]
t=10: [x_10, y_10, z_10, "A"]
t=11: [x_11, y_11, z_11, "A"]
t=12: [x_12, y_12, z_12, "A"]
...
t=0: [RA, Dec, z_0, "A"]
t=1: [RA, Dec, z_1, "A"]
t=2: [RA, Dec, z_2, "A"]
t=3: [RA, Dec, z_3, "A"]
t=4: [RA, Dec, z_4, "A"]
t=5: [RA, Dec, z_5, "B"]
t=6: [RA, Dec, z_6, "B"]
t=7: [RA, Dec, z_7, "B"]
t=8: [RA, Dec, z_8, "B"]
t=9: [RA, Dec, z_9, "B"]
...

t=0: [RA, Dec, z_0, "A", "Entity1", "Rotational Symmetry"]
t=1: [RA, Dec, z_1, "A", "Entity1", "Rotational Symmetry"]
t=2: [RA, Dec, z_2, "A", "Entity1", "Rotational Symmetry"]
t=3: [RA, Dec, z_3, "A", "Entity1", "Rotational Symmetry"]
t=4: [RA, Dec, z_4, "A", "Entity1", "Rotational Symmetry"]
t=5: [RA, Dec, z_5, "B", "Entity1", "Rotational Symmetry"]
t=6: [RA, Dec, z_6, "B", "Entity1", "Rotational Symmetry"]
t=7: [RA, Dec, z_7, "B", "Entity1", "Rotational Symmetry"]
t=8: [RA, Dec, z_8, "B", "Entity1", "Rotational Symmetry"]
t=9: [RA, Dec, z_9, "B", "Entity1", "Rotational Symmetry"]
...
t=0: [RA, Dec, z_0, "A", "Entity1", "Rotational Symmetry"]
t=1: [RA, Dec, z_1, "A", "Entity1", "Rotational Symmetry"]
t=2: [RA, Dec, z_2, "A", "Entity1", "Rotational Symmetry"]
...
t=18: [RA, Dec, z_18, "B", "Entity1", "Rotational Symmetry"]
t=19: [RA, Dec, z_19, "B", "Entity1", "Rotational Symmetry"]
t=20: [RA, Dec, z_20, "None", "Entity1", "None"]
